name: Publish Html

on:
  push:
    branches:
      - master
      - develop
      - release-*
  pull_request:
    branches:
      - master
      - develop
      - release-*
    types:
      - open
      - synchronize


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Make Html
        run: docker run --rm -v "${PWD}:/doc" -u "$(id -u):$(id -g)" ohiosupercomputer/docker-sphinx make html

      - name: check env
        run: env | grep GITHUB
