name: Publish Html

on:
  push:
  pull_request:
    branches:
      - master
      - develop
      - release-*
    types:
      - open
      - synchronize


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Make Html
        run: docker --rm -t -v "${PWD}:/doc" -u "$(id -u):$(id -g)" ohiosupercomputer/docker-sphinx make html
