name: Publish Html

on:
  push:
  pull_request:
    branches:
      - master
      - develop
      - release-*
    types:
      - open
      - synchronize


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: Make HTML

