name: Publish Html

on:
  push:
    branches: [master, develop, release-*]
  pull_request:
    branches: [master, develop, release-*]
    types: [open, synchronize, reopen]


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Make Html
        run: docker run --rm -v "${PWD}:/doc" -u "$(id -u):$(id -g)" ohiosupercomputer/docker-sphinx make html

      - name: Publish to the test repo
        run: /bin/bash push.sh "ood-documentation-test"
        with:
          GITHUB_TOKEN: ${{ OSC_WIAG_PUB_REPO_TOKEN }}
    
      - name: Publish to the main repo
        if: github.event_name == 'push'
        run: /bin/bash push.sh "ood-documentation"
        with:
          GITHUB_TOKEN: ${{ OSC_WIAG_PUB_REPO_TOKEN }}
